import { useCameraPermissions } from 'expo-camera';
import { act, fireEvent, renderRouter, screen } from 'expo-router/testing-library';

import { useSessionStore } from '@/session/store';

import { resetApp } from './support/app';

/**
 * O que este teste prova é a ligação entre as três peças — câmara, `parseQr` e store. As regras de
 * leitura em si estão cobertas em `src/qr/parse.test.ts`, que não precisa de ecrã nenhum.
 */
describe('ecrã de leitura de QR', () => {
  beforeEach(() => {
    resetApp();
    jest
      .mocked(useCameraPermissions)
      .mockReturnValue([
        { granted: true, canAskAgain: true, status: 'granted', expires: 'never' },
        jest.fn(() => Promise.resolve(null)),
      ] as unknown as ReturnType<typeof useCameraPermissions>);
  });

  /** Dispara um código como a câmara real o dispararia — pela prop do `CameraView`. */
  const scan = async (data: string) => {
    const camera = await screen.findByTestId('camera');
    await act(async () => {
      camera.props.onBarcodeScanned?.({ type: 'qr', data });
    });
  };

  it('abre-se a partir do ecrã de ligar', async () => {
    const router = renderRouter('./app', { initialUrl: '/connect' });
    await router;

    await fireEvent.press(await screen.findByText('Scan QR'));

    expect(router.getPathname()).toBe('/scan');
  });

  it('liga com o payload do contrato e usa o base_url que vem no QR', async () => {
    const router = renderRouter('./app', { initialUrl: '/scan' });
    await router;

    await scan(JSON.stringify({ v: 1, base_url: 'https://staging.esgrima.pt', pin: '483920' }));

    await screen.findByText('Poule 3 — Sabre Masculino');
    expect(router.getPathname()).toBe('/poule');
    expect(useSessionStore.getState().baseUrl).toBe('https://staging.esgrima.pt');
    expect(useSessionStore.getState().phase).toBe('poule');
  });

  it('liga com um QR de só seis dígitos — é o que a plataforma gera hoje', async () => {
    const router = renderRouter('./app', { initialUrl: '/scan' });
    await router;

    await scan('483920');

    await screen.findByText('Poule 3 — Sabre Masculino');
    expect(router.getPathname()).toBe('/poule');
    // Sem `base_url` no código, fica o valor por omissão — a app não pergunta o servidor a ninguém.
    expect(useSessionStore.getState().baseUrl).toBe('https://poole.esgrima.pt');
  });

  it('mostra a razão de um QR que não serve e não liga', async () => {
    const router = renderRouter('./app', { initialUrl: '/scan' });
    await router;

    await scan('https://esgrima.pt/qualquer-coisa');

    expect(
      screen.getByText('QR code not recognised. Check that it is the code on the poule sheet.'),
    ).toBeTruthy();
    expect(router.getPathname()).toBe('/scan');
    expect(useSessionStore.getState().phase).toBe('disconnected');
  });

  it('para de ler enquanto o erro está no ecrã, e volta a ler no "Scan again"', async () => {
    await renderRouter('./app', { initialUrl: '/scan' });

    await scan('nada');
    // Com o erro no ecrã a câmara está desligada — o mesmo código mau não se relê sozinho.
    expect(screen.getByTestId('camera').props.onBarcodeScanned).toBeUndefined();

    await fireEvent.press(screen.getByText('Scan again'));

    expect(screen.getByTestId('camera').props.onBarcodeScanned).toEqual(expect.any(Function));
  });

  it('não liga duas vezes quando o mesmo código chega em frames seguidos', async () => {
    const connect = jest.spyOn(useSessionStore.getState(), 'connect');
    await renderRouter('./app', { initialUrl: '/scan' });
    const camera = await screen.findByTestId('camera');

    // Os dois frames no mesmo `act`: é assim que a câmara real entrega — o segundo chega antes de
    // o React sequer voltar a desenhar, quanto mais de a rota seguinte montar.
    await act(async () => {
      camera.props.onBarcodeScanned({ type: 'qr', data: '483920' });
      camera.props.onBarcodeScanned({ type: 'qr', data: '483920' });
    });

    expect(connect).toHaveBeenCalledTimes(1);
    connect.mockRestore();
  });

  it('explica a versão desconhecida em vez de dizer que o QR não presta', async () => {
    await renderRouter('./app', { initialUrl: '/scan' });

    await scan(JSON.stringify({ v: 9, base_url: 'https://poole.esgrima.pt', pin: '483920' }));

    expect(
      screen.getByText(
        'This QR code was generated by a newer version of the platform. Update the app.',
      ),
    ).toBeTruthy();
  });

  it('sem permissão, oferece pedi-la e o caminho do PIN', async () => {
    const requestPermission = jest.fn(() => Promise.resolve(null));
    jest
      .mocked(useCameraPermissions)
      .mockReturnValue([
        { granted: false, canAskAgain: true, status: 'undetermined', expires: 'never' },
        requestPermission,
      ] as unknown as ReturnType<typeof useCameraPermissions>);

    await renderRouter('./app', { initialUrl: '/scan' });

    await fireEvent.press(await screen.findByText('Allow camera'));
    expect(requestPermission).toHaveBeenCalled();
    expect(screen.getByText('Enter the PIN instead')).toBeTruthy();
  });

  it('negada em definitivo, manda às Definições em vez de repetir um pedido que não aparece', async () => {
    const requestPermission = jest.fn(() => Promise.resolve(null));
    jest
      .mocked(useCameraPermissions)
      .mockReturnValue([
        { granted: false, canAskAgain: false, status: 'denied', expires: 'never' },
        requestPermission,
      ] as unknown as ReturnType<typeof useCameraPermissions>);

    await renderRouter('./app', { initialUrl: '/scan' });

    expect(await screen.findByText('Open Settings')).toBeTruthy();
    expect(screen.queryByText('Allow camera')).toBeNull();
  });
});
